name: CI Pipeline

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for DVC

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[cml] pytest dvc-gs

      # 4. Pull DVC data & model
      - name: Pull data and model with DVC
        run: |
          touch gcrypto-shore-473811-r3-d46360224002.json
          printf "%s" "${{ secrets.GCP_SA_KEY }}" > gcrypto-shore-473811-r3-d46360224002.json
          export GOOGLE_APPLICATION_CREDENTIALS=$PWD/gcrypto-shore-473811-r3-d46360224002.json
          dvc remote modify --local gcsremote credentialpath $PWD/gcrypto-shore-473811-r3-d46360224002.json
          dvc pull -v
          
      # 5. Run pytest
      - name: Run tests and create report
        run: |
          mkdir -p reports
          echo "## Pytest Sanity Report" > reports/report.md
          echo "" >> reports/report.md
          pytest -v tests/ --maxfail=1 --disable-warnings --tb=short >> reports/report.md
      
      # 6. Set up CML
      - name: Set up CML
        uses: iterative/setup-cml@v2
        with:
          version: 'latest'
      
      # 7. Post report as comment
      - name: Post CML comment
        run: |
          cml comment create --publish reports/report.md
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
