name: CI Pipeline

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for DVC

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[cml] pytest

      # 4. Pull DVC data & model
      - name: Pull data and model with DVC
        run: |
          printf "%s" "${{ secrets.GCP_SA_KEY }}" > gcrypto-shore-473811-r3-d46360224002.json
          export GOOGLE_APPLICATION_CREDENTIALS=$PWD/gcrypto-shore-473811-r3-d46360224002.json
          dvc pull
        env:
          DVC_REMOTE: ${{ secrets.DVC_REMOTE }}  # optional, if you use a remote

      # 5. Run pytest
      - name: Run tests
        run: |
          pytest -v tests/ --junitxml=reports/results.xml

      # 6. Generate CML report (sanity check)
      - name: Run CML report
        uses: iterative/cml@v3
        with:
          report-type: html
          file: reports/results.xml
          text: "Sanity test report"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
